package com.omnidocs.app.study

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.omnidocs.app.util.HtmlSanitizer
import java.io.File
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Service for exporting study decks, flashcards, and quizzes into
 * standard Markdown formats and Anki-compatible TSV files with share sheet integration.
 */
@Singleton
class StudyExportService @Inject constructor() {

    /**
     * Serializes a study deck into standard Markdown flashcard format.
     */
    fun exportToMarkdown(deck: StudyDeck): String {
        return buildString {
            appendLine("# Flashcards: ${deck.title}")
            appendLine()
            appendLine("> Generated by OmniDocs Study Intelligence. Compatible with Obsidian Spaced Repetition and standard Markdown readers.")
            appendLine()

            deck.cards.forEachIndexed { idx, card ->
                appendLine("## Card ${idx + 1}")
                when (card.type) {
                    StudyCardType.QA -> {
                        appendLine("**Question:** ${card.prompt}")
                        appendLine()
                        appendLine("**Answer:** ${card.answer}")
                    }
                    StudyCardType.CLOZE -> {
                        appendLine("**Cloze:** ${card.prompt}")
                        appendLine()
                        appendLine("**Answer:** ${card.answer}")
                    }
                    StudyCardType.MULTIPLE_CHOICE -> {
                        appendLine("**Question:** ${card.prompt}")
                        appendLine()
                        card.options.forEachIndexed { optIdx, opt ->
                            val marker = if (optIdx == card.correctOptionIndex) "(✓)" else "( )"
                            appendLine("- $marker $opt")
                        }
                        appendLine()
                        appendLine("**Correct Answer:** ${card.answer}")
                    }
                    StudyCardType.DEFINITION -> {
                        appendLine("**Term:** ${card.prompt}")
                        appendLine()
                        appendLine("**Definition:** ${card.answer}")
                    }
                }

                if (!card.explanation.isNullOrBlank()) {
                    appendLine()
                    appendLine("*Explanation:* ${card.explanation}")
                }

                val sourceTitle = card.sourceTitle?.takeIf { it.isNotBlank() }
                val snippet = card.sourceSnippet?.takeIf {
                    it.isNotBlank() &&
                        !it.contains("[Truncated", ignoreCase = true) &&
                        !it.contains("Truncated text", ignoreCase = true)
                }
                if (sourceTitle != null || snippet != null) {
                    appendLine()
                    val titlePart = if (sourceTitle != null) "**Source:** $sourceTitle" else "**Source:**"
                    val snippetPart = if (snippet != null) " — *\"$snippet\"*" else ""
                    appendLine("> $titlePart$snippetPart")
                }

                if (card.tags.isNotEmpty()) {
                    appendLine()
                    appendLine("Tags: ${card.tags.joinToString(" ") { "#$it" }}")
                }

                appendLine()
                appendLine("---")
                appendLine()
            }
        }.trim()
    }

    /**
     * Serializes a study deck into Anki-compatible TSV format (Tab-Separated Values).
     */
    fun exportToAnkiTsv(deck: StudyDeck): String {
        return buildString {
            appendLine("#separator:tab")
            appendLine("#html:true")
            appendLine("#tags column:3")

            deck.cards.forEach { card ->
                val front = escapeTsv(card.prompt)
                val back = buildString {
                    append(escapeTsv(card.answer))
                    if (!card.explanation.isNullOrBlank()) {
                        append("<br/><br/><i>${escapeTsv(card.explanation)}</i>")
                    }
                    val sourceTitle = card.sourceTitle?.takeIf { it.isNotBlank() }
                    val snippet = card.sourceSnippet?.takeIf {
                        it.isNotBlank() &&
                            !it.contains("[Truncated", ignoreCase = true) &&
                            !it.contains("Truncated text", ignoreCase = true)
                    }
                    val sourceHtml = when {
                        sourceTitle != null && snippet != null ->
                            "<br/><br/><small><b>Source:</b> ${escapeTsv(sourceTitle)} — <i>\"${escapeTsv(snippet)}\"</i></small>"
                        sourceTitle != null ->
                            "<br/><br/><small><b>Source:</b> ${escapeTsv(sourceTitle)}</small>"
                        snippet != null ->
                            "<br/><br/><small>Source: \"${escapeTsv(snippet)}\"</small>"
                        else -> ""
                    }
                    if (sourceHtml.isNotBlank()) {
                        append(sourceHtml)
                    }
                }
                val tags = card.tags.joinToString(" ")

                appendLine("$front\t$back\t$tags")
            }
        }.trim()
    }

    /**
     * Shares exported study deck via the Android system share sheet.
     */
    fun shareStudyDeck(
        context: Context,
        content: String,
        isMarkdown: Boolean = true,
        baseFilename: String = "flashcards"
    ): Boolean {
        return try {
            val extension = if (isMarkdown) "md" else "txt"
            val mimeType = if (isMarkdown) "text/markdown" else "text/tab-separated-values"
            val exportDir = File(context.cacheDir, "exports")
            exportDir.mkdirs()
            val fileName = "${baseFilename}_${System.currentTimeMillis()}.$extension"
            val file = File(exportDir, fileName)
            file.writeText(content, Charsets.UTF_8)

            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = mimeType
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_SUBJECT, "OmniDocs Study Deck Export ($extension)")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }

            val chooser = Intent.createChooser(intent, "Share Study Deck").apply {
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(chooser)
            true
        } catch (e: Exception) {
            android.util.Log.e("StudyExportService", "Failed to share study deck", e)
            false
        }
    }

    private fun escapeTsv(text: String): String {
        val sanitized = HtmlSanitizer.sanitize(text)
        return sanitized
            .replace("\t", " ")
            .replace("\r\n", "<br/>")
            .replace("\n", "<br/>")
            .replace("\"", "&quot;")
    }
}
